"""baseline: existing schema

Revision ID: 7a537cfe8180
Revises: 
Create Date: 2026-08-31 02:02:05.900700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a537cfe8180'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('latest_snapshot_id', sa.String(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_identifier', sa.String(length=256), nullable=False),
    sa.Column('annotation_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inferred_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('evidence_data', sa.JSON(), nullable=False),
    sa.Column('inferred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['schema_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('relationship_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('corrected_source_column', sa.String(), nullable=True),
    sa.Column('corrected_target_table', sa.String(), nullable=True),
    sa.Column('corrected_target_column', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['inferred_relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_decisions')
    op.drop_table('inferred_relationships')
    op.drop_table('semantic_annotations')
    op.drop_table('schema_snapshots')
    op.drop_table('dataset_plans')
    op.drop_table('projects')
    # ### end Alembic commands ###
